# 0. Importando o dataset

In [290]:
import pandas as pd
import plotly.express as px

url = "https://raw.githubusercontent.com/ingridcristh/challenge2-data-science/refs/heads/main/TelecomX_Data.json"

In [291]:
df = pd.read_json(url)
df.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

# 1. Tratamento de dados inicial

In [292]:
def normalizar_coluna(lista_coluna,df):
    for Coluna in lista_coluna:
        _ = pd.json_normalize(df[Coluna])
        df.drop(columns=Coluna, inplace=True)
        df = pd.concat([df, _], axis=1)
    return df

lista_coluna = ['customer', 'phone', 'internet', 'account']
df = normalizar_coluna(lista_coluna,df)
df.head()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [293]:
df.columns = df.columns.str.replace(r'(?<=[a-z0-9])([A-Z])|([.])', r'_\1', regex=True).str.lower()
df.head()

,customer_id,churn,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,charges_monthly,charges_total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [294]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        7267 non-null   object
 1   churn              7267 non-null   object
 2   gender             7267 non-null   object
 3   senior_citizen     7267 non-null   int64
 4   partner            7267 non-null   object
 5   dependents         7267 non-null   object
 6   tenure             7267 non-null   int64
 7   phone_service      7267 non-null   object
 8   multiple_lines     7267 non-null   object
 9   internet_service   7267 non-null   object
 10  online_security    7267 non-null   object
 11  online_backup      7267 non-null   object
 12  device_protection  7267 non-null   object
 13  tech_support       7267 non-null   object
 14  streaming_tv       7267 non-null   object
 15  streaming_movies   7267 non-null   object
 16  contract           7267 non-null   object
 17  paperless_billing  7267 non-null   object
 18  payment_method     7267 non-null   object
 19  charges_monthly    7267 non-null   float64
 20  charges_total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [295]:
df.duplicated().sum()

np.int64(0)

In [296]:
df.loc[df['charges_total'] == ' ']

,customer_id,churn,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,charges_monthly,charges_total
975,1371-DWPAZ,No,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,
1775,2520-SGTTA,No,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,
1955,2775-SEFEE,No,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,
2075,2923-ARZLG,No,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,
2232,3115-CZMZD,No,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,
2308,3213-VVOLG,No,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,
2930,4075-WKNIU,No,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,
3134,4367-NUYAO,No,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,
3203,4472-LVYGI,No,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,
4169,5709-LVOEQ,No,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,
5599,7644-OMVMY,No,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,

In [297]:
# Dado que o ternure é 0, é perceptível que esses clientes são novos e ainda não possuem gastos totais, então vamos substituir os valores vazios por 0.0
df.loc[df['charges_total'] == ' ', 'charges_total'] = 0.0
df.loc[:,'charges_total'] = df.loc[:,'charges_total'].astype(float)

In [298]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        7267 non-null   object
 1   churn              7267 non-null   object
 2   gender             7267 non-null   object
 3   senior_citizen     7267 non-null   int64
 4   partner            7267 non-null   object
 5   dependents         7267 non-null   object
 6   tenure             7267 non-null   int64
 7   phone_service      7267 non-null   object
 8   multiple_lines     7267 non-null   object
 9   internet_service   7267 non-null   object
 10  online_security    7267 non-null   object
 11  online_backup      7267 non-null   object
 12  device_protection  7267 non-null   object
 13  tech_support       7267 non-null   object
 14  streaming_tv       7267 non-null   object
 15  streaming_movies   7267 non-null   object
 16  contract           7267 non-null   object
 17  paperless_billing  7267 non-null   object
 18  payment_method     7267 non-null   object
 19  charges_monthly    7267 non-null   float64
 20  charges_total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [299]:
pd.set_option('display.max_columns', None)
df.head()

,customer_id,churn,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,charges_monthly,charges_total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [300]:
df.drop(columns=['customer_id'], inplace=True)
df

,churn,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,charges_monthly,charges_total
0,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,No,Female,0,No,No,13,Yes,No,DSL,Yes,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,No,Male,0,No,No,2,Yes,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,No,Male,0,Yes,Yes,67,Yes,No,DSL,Yes,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,No,Male,0,Yes,Yes,63,No,No phone service,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

# 2. Análise gráfica dos dados

### 2.1 Visualização dados categóricos

In [301]:
px.histogram(df, x='churn', color='churn', title='Distribuição de Churn')

In [302]:
df.loc[df['churn'] == '']

,churn,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,charges_monthly,charges_total
30,,Female,0,No,No,11,Yes,Yes,Fiber optic,Yes,No,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),79.00,929.3
75,,Male,0,No,No,71,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card (automatic),19.90,1355.1
96,,Male,0,No,No,29,Yes,No,DSL,Yes,Yes,No,Yes,No,No,One year,Yes,Electronic check,58.75,1696.2
98,,Female,1,No,No,5,Yes,No,DSL,Yes,Yes,No,Yes,No,No,Month-to-month,No,Credit card (automatic),59.90,287.85
175,,Male,1,Yes,No,65,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Bank transfer (automatic),103.15,6792.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7158,,Female,0,No,No,14,Yes,Yes,DSL,No,Yes,No,No,No,No,One year,Yes,Mailed check,54.25,773.2
7180,,Female,0,Yes,No,49,No,No phone service,DSL,Yes,No,No,No,Yes,No,Month-to-month,No,Bank transfer (automatic),40.65,2070.75
7211,,Male,0,No,No,9,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,76.25,684.85
7239,,Female,0,Yes,Yes,67,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),19.25,1372.9
7247,,Female,0,Yes,Yes,31,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check,19.55,658.95

In [303]:
# Esses dados não irão ajudar a gente analisar o churn, então vamos retirar eles do nosso dataframe
df = df[df['churn'] != '']
px.histogram(df, x='churn', color='churn', title='Distribuição de Churn')

In [304]:
lista_colunas_categoricas = ['gender', 'senior_citizen', 'partner', 'dependents', 'phone_service', 'multiple_lines', 'internet_service',
'online_security', 'online_backup', 'device_protection', 'tech_support', 'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing', 'payment_method']
df[lista_colunas_categoricas].nunique()

gender               2
senior_citizen       2
partner              2
dependents           2
phone_service        2
multiple_lines       3
internet_service     3
online_security      3
online_backup        3
device_protection    3
tech_support         3
streaming_tv         3
streaming_movies     3
contract             3
paperless_billing    2
payment_method       4
dtype: int64

In [305]:
for i in lista_colunas_categoricas:
    fig = px.histogram(df, x= i, color='churn', barmode= 'group')
    fig.show()

In [306]:
df = df.copy()
df['feature_citizen'] = df['senior_citizen']
df['senior_citizen'] = df['senior_citizen'].map({0: 'No', 1: 'Yes'})
px.histogram(df, x='senior_citizen', color='churn', barmode= 'group' , title='Distribuição de Churn')

In [307]:
df['senior_citizen']

0        No
1        No
2        No
3       Yes
4       Yes
       ...
7262     No
7263     No
7264     No
7265     No
7266     No
Name: senior_citizen, Length: 7043, dtype: object

### 2.2 Visualização dos dados numéricos

In [308]:
px.box(df,x='tenure', color = 'churn', title='Boxplot de Tenure por Churn')

In [309]:
px.box(df, x='charges_monthly', color = 'churn', title='Boxplot de gasto mensal por Churn')

In [310]:
px.box(df, x='charges_total', color = 'churn', title='Boxplot de gasto total por Churn')

In [311]:
lista_colunas_numericas = ['tenure', 'charges_monthly', 'charges_total']
for i in lista_colunas_numericas:
    print(f'A média de {i} é: {df[i].mean():.2f}')

A média de tenure é: 32.37
A média de charges_monthly é: 64.76
A média de charges_total é: 2279.73

# 3. Relatório das informações

## Relatório de Análise de Evasão de Clientes (Churn)

### Introdução  

O presente relatório tem como objetivo analisar os fatores associados à evasão de clientes (churn) em uma base de dados de serviços de telecomunicações. A evasão de clientes representa um dos principais desafios estratégicos para empresas do setor, impactando diretamente a receita recorrente e os custos operacionais, uma vez que a aquisição de novos clientes tende a ser significativamente mais onerosa do que a retenção dos atuais.  

A análise busca identificar padrões comportamentais e características contratuais associadas a maiores taxas de churn, a fim de fornecer subsídios para ações estratégicas voltadas à retenção de clientes.

---

### Limpeza e Tratamento de Dados  

Inicialmente, os dados foram importados e submetidos a um processo de verificação de inconsistências, incluindo análise de valores ausentes, duplicados e possíveis erros de tipagem.  

Foram realizadas as seguintes etapas de tratamento:

- Conversão de variáveis categóricas codificadas numericamente para rótulos interpretáveis quando necessário para análise visual.
- Padronização de nomes de colunas para garantir consistência e legibilidade.
- Conversão de variáveis numéricas armazenadas como texto para o tipo apropriado.

Essas etapas asseguraram maior confiabilidade e clareza na análise exploratória subsequente.

---

### Análise Exploratória de Dados  

A análise exploratória foi conduzida por meio de histogramas e gráficos de caixa e comparação entre grupos.

#### Variáveis Demográficas  

- **Gênero:** Não foram observadas diferenças significativas no comportamento de evasão entre os gêneros. As proporções de churn se mostraram semelhantes entre as classes.
  
- **Senioridade (idosos acima de 65 anos):** Observou-se uma proporção relativamente maior de churn entre clientes idosos. No entanto, o volume reduzido de clientes nessa faixa etária limita conclusões mais robustas.

- **Presença de parceiro(a):** Clientes sem parceiro(a) apresentam quase o dobro de evasão em termos absolutos, indicando uma tendência relevante.

- **Dependentes:** Foi identificada uma diferença significativa: clientes sem dependentes apresentam um churn aproximadamente cinco vezes maior, mesmo considerando um leve desbalanceamento entre os grupos.

---

#### Serviços Contratados  

- **Serviço telefônico e múltiplas linhas:** Não foram identificados padrões relevantes de evasão.

- **Serviço de internet:** Observou-se uma taxa de churn significativamente elevada entre clientes que utilizam fibra óptica, sugerindo possível insatisfação ou problemas relacionados a esse serviço.

- **Segurança online, backup online e proteção de dispositivos:** Clientes que não possuem esses serviços apresentam maior taxa de evasão. A ausência de segurança online e backup demonstrou associação particularmente perceptível com churn.

- **Assistência técnica:** A ausência desse serviço também está associada a maior evasão.

- **Serviços de streaming (TV e filmes):** Foi identificada uma leve tendência de maior churn entre clientes que não possuem esses serviços, porém o efeito é menos expressivo.

---

#### Tipo de Contrato e Método de Pagamento  

- **Contrato mensal:** Apresenta a maior taxa de churn observada na análise. Clientes com contrato mensal demonstram evasão significativamente superior aos demais tipos de contrato.

- **Faturamento online:** Clientes que optam por faturamento eletrônico apresentam maior evasão.

- **Cheque eletrônico:** Este método de pagamento mostrou-se fortemente associado a altos índices de churn, configurando um dos pontos mais críticos identificados.

---

#### Variáveis Numéricas  

- **Tempo de permanência (tenure):** Clientes com menor tempo de permanência apresentam maior churn, padrão comum em serviços por assinatura.

- **Gasto mensal:** Clientes que evadiram tendem a apresentar gasto mensal mediano mais elevado.

- **Gasto total:** Observou-se valor total menor entre clientes que evadiram, o que está diretamente relacionado ao menor tempo de permanência no serviço.

---

### Conclusões e Insights  

A análise identificou três fatores principais associados à elevada evasão:

1. Contratos mensais  
2. Método de pagamento por cheque eletrônico  
3. Serviço de internet por fibra óptica  

Além disso, a ausência de serviços adicionais (segurança online, backup e proteção) também está associada a maior churn.  

Clientes com menor tempo de permanência representam o grupo mais vulnerável à evasão, indicando a importância de estratégias de retenção nos primeiros meses de contrato.

---

### Recomendações  

Com base nos achados, recomenda-se:

1. **Revisão do modelo de contrato mensal**, incentivando migração para contratos de maior duração por meio de benefícios ou descontos.
2. **Investigação da experiência do cliente no serviço de fibra óptica**, incluindo análise de qualidade, suporte técnico e estabilidade.
3. **Reavaliação do método de pagamento por cheque eletrônico**, considerando simplificação ou incentivos para métodos alternativos.
4. **Criação de pacotes combinados** (internet + segurança online + backup), agregando valor percebido e reduzindo probabilidade de churn.
5. **Estratégias de retenção nos primeiros meses de contrato**, como acompanhamento ativo, ofertas personalizadas ou benefícios progressivos.

A implementação dessas ações pode contribuir significativamente para a redução da taxa de evasão e aumento do valor do ciclo de vida do cliente.

# 4. Salvando o modelo para o próximo desafio

In [312]:
df.to_csv('telecom_churn.csv', index=False)